apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  APP_MESSAGE: "Welcome to version 1"




apiVersion: v1
kind: Pod
metadata:
  name: demo-config-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "while true; do echo $APP_MESSAGE; sleep 5; done"]
    env:
    - name: APP_MESSAGE
      valueFrom:
        configMapKeyRef:
          name: demo-config
          key: APP_MESSAGE



# kubectl logs demo-config-pod
# Change the configmap yaml file as below msg APP_MESSAGE: "Welcome to version 2"
# Delete the pod kubectl delete pod demo-config-pod
# kubectl logs demo-config-pod
# In output need to check msg has to be changed


