# To demonstrate the resource in deployment
apiVersion: v1
kind: Pod
metadata:
  name: nginx-resources
  namespace: dev-team
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# To check quota usage kubectl describe quota dev-team-quota -n dev-team

