apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80            # Service port (internal cluster)
    targetPort: 80      # Container port
    nodePort: 30080     # External port (range: 30000-32767)
