
# echo -n 'admin' | base64       command is used to convert value to base64

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=      # base64 of 'admin'
  password: TXlTZWNyZXQxMjM=  # base64 of 'MySecret123'





apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKERCONFIG>

# Replace <BASE64_ENCODED_DOCKERCONFIG> with the base64-encoded content of your .docker/config.json.

How to Generate .dockerconfigjson and Encode It
docker login
cat ~/.docker/config.json | base64 -w 0     # This generates ~/.docker/config.json. To base64-encode it:
Paste the encoded output into the .dockerconfigjson field in the YAML.

apiVersion: v1
kind: Pod
metadata:
  name: nginx-private
spec:
  containers:
  - name: nginx
    image: your-private-repo/nginx:tag
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred
