---
- hosts: all
  tasks:
    - name: wrong package install
      apt: 
        name: git1
        state: present
      ignore_errors: yes
      register: error_message
    - name: fail if failed status
      fail:
        msg: "The state is failed"
      when: error_message.failed == true
