---
- hosts: all
  tasks:
    - name: install a git
      apt:
        name: git
        state: present
    - name: copy a file
      copy: 
        src: /home/ubuntu/2.txt
        dest: /home/ubuntu/
    - name: changing the file mode 
      file:
        path: /home/ubuntu/1.txt
        mode: 0764
        owner: root
        group: root
    - name: create a new file with new content
      copy: 
        content: "Welcome" 
        dest: "/home/ubuntu/new.txt"
        backup: yes
        owner: root
        group: root
        mode: 0644
    - name: to copy a template
      template:
        src: /home/ubuntu/1.j2
        dest: /home/ubuntu/
