---
- hosts: all
  tasks:
    - name: apache_install
      when: ansible_distribution == "Ubuntu"
      apt:
        name: apache2
        state: present
    - name: apache_install
      when: ansible_distribution == "centos"
      yum:
        name: apache2
        state: present
    - command: systemcl status apache2
      register: apache_service
    - debug:
      var: apache_service.stdout_lines
    - name: checking date
      shell:
        "date"
      register: datecmd
    - debug: 
        var: datecmd.stdout_lines
    - name: listing_files
      shell: ls
      register: list_values
    - debug:
        var: list_values
    - name: displaying_files
      shell: cat "{{ item }}"
      with_items: "{{ list_values.stdout_lines }}"
      register: cat_output
    - debug:
        var: cat_output
